export const themeLookup = {
  baseGeometry: {
    colors: {
      pointColor: "#BBB",
      controlPointColor: "#BBB",
      handleLineColor: "#BBB",
      curveStrokeColor: "#000",
      curveUnderStrokeColor: "#FFF6",
      fillColor: "rgb(230, 15, 15)",
      selectedPointColor: "#000",
      selectedControlPointColor: "#000",
      selectedHandleLineColor: "#000",
      hoveredPointStrokeColor: "#BBB",
    },
    sizes: {
      curveStrokeWidth: 1,
      curveUnderStrokeWidth: 3,
      handleStrokeWidth: 1,
      pointSize: 8,
      controlPointSize: 6.5,
    },
  },
  skeletonGeometry: {
    colors: {
      skeletonPointColor: "#0080FF",
      skeletonControlPointColor: "#0080FF",
      skeletonCurveColor: "#0080FF",
      ribLineColor: "rgba(0, 128, 255, 0.4)",
      ribPointColor: "rgba(220, 60, 120, 0.7)",
      ribPointHoverColor: "rgba(220, 60, 120, 1.0)",
      selectedSkeletonPointColor: "#FF4000",
      selectedSkeletonControlPointColor: "#FF4000",
      selectedRibPointColor: "rgba(255, 64, 0, 0.9)",
      ribPointEditableColor: "rgba(160, 40, 180, 0.9)",
      ribPointEditableHoverColor: "rgba(160, 40, 180, 1.0)",
      ribPointEditableSelectedColor: "rgba(160, 40, 180, 1.0)",
      skeletonHandleLineColor: "rgba(0, 128, 255, 0.6)",
    },
    sizes: {
      skeletonStrokeWidth: 1.5,
      ribStrokeWidth: 1,
      skeletonHandleStrokeWidth: 1,
      skeletonPointSize: 7,
      skeletonControlPointSize: 5,
      ribPointSize: 10,
      ribEditablePointSize: 12,
    },
  },
  powerRuler: {
    light: {
      strokeColor: "#0004",
      insideBlobColor: "#FFFB",
      insideTextColor: "#000B",
      outsideBlobColor: "#000B",
      outsideTextColor: "#FFFB",
      intersectionColor: "#F085",
    },
    dark: {
      strokeColor: "#FFF6",
      insideBlobColor: "#444B",
      insideTextColor: "#FFFB",
      outsideBlobColor: "#FFFB",
      outsideTextColor: "#444B",
      intersectionColor: "#F696",
    },
    sizes: {
      strokeWidth: 1,
      fontSize: 12,
      intersectionRadius: 4,
    },
  },
};
